{{- if or (and .Values.openstack.username .Values.openstack.password) (and .Values.openstack.application_credential_id .Values.openstack.application_credential_secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "cloud-config" .Values.credentialsSecret }}
  labels:
    app: "{{ template "designate-certmanager-webhook.fullname" . }}"
    chart: "{{ template "designate-certmanager-webhook.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.openstack.username }}
  username: {{ .Values.openstack.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.password }}
  password: {{ .Values.openstack.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.application_credential_id }}
  application-credential-id: {{ .Values.openstack.application_credential_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.application_credential_secret }}
  application-credential-secret: {{ .Values.openstack.application_credential_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.project_id }}
  tenant-id: {{ .Values.openstack.project_id | b64enc | quote }}
  {{- else if .Values.openstack.project_name }}
  tenant-name: {{ .Values.openstack.project_name | b64enc | quote }}
  {{- else }}
    {{- if ne .Values.openstack.auth_type "v3applicationcredential" }}
      {{- fail "project_id or project_name is needed!" }}
    {{- end }}
  {{- end }}
  {{- if .Values.openstack.region_name }}
  region: {{ .Values.openstack.region_name | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.auth_url }}
  auth-url: {{ .Values.openstack.auth_url | b64enc | quote }}
  {{- end }}
  {{- if .Values.openstack.domain_name }}
  domain-name: {{ .Values.openstack.domain_name | b64enc | quote }}
  {{- end }}
{{- end }}
